[package]
name = "valkyrie-keymap"
version = "0.2.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3.9", features = [
    "minwindef",
    "libloaderapi",
    "winuser",
] }
rodio = "0.19.0"

[profile.release]
opt-level = 3
lto = true
