[package]
name = "valkyrie-keymap"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = ["minwindef", "libloaderapi", "winuser"] }

[profile.release]
opt-level = 3
lto = true